In [224]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import re

In [225]:
# Ruta del archivo .csv
file_path = r'C:\Users\Usuario\Desktop\HENRY\PROYECTO FINAL\CENSO\alquilerCONDADO.csv'

# Cargar el archivo .csv y seleccionar columnas espec√≠ficas
columnas_necesarias = ['RegionName', 'renta']  # Cambia por los nombres de las columnas que necesitas
df_alquilerCONDADO = pd.read_csv(file_path, usecols=columnas_necesarias)

In [226]:
condados_a_ciudades = {
    'Alameda': ['Alameda', 'Albany', 'Berkeley', 'Dublin', 'Emeryville', 'Fremont', 'Hayward', 'Livermore', 'Newark', 'Oakland', 'Pleasanton', 'San Leandro', 'Union City', 'Castro Valley', 'San Lorenzo'],
    'Alpine': ['Markleeville', 'Markleeville'],
    'Amador': ['Amador City', 'Ione', 'Jackson', 'Plymouth', 'Sutter Creek', 'Jackson'],
    'Butte': ['Biggs', 'Chico', 'Gridley', 'Oroville', 'Durham', 'Paradise', 'Chico', 'Magalia', 'Paradise'],
    'Calaveras': ['Angels Camp', 'Copperopolis', 'Arnold', 'San Andreas'],
    'Colusa': ['Colusa', 'Williams', 'Colusa', 'Princeton'],
    'Contra Costa': ['Alameda Park', 'Antioch', 'Brentwood', 'Clayton', 'Concord', 'Crockett', 'Danville', 'El Cerrito', 'Hercules', 'Lafayette', 'Martinez', 'Moraga', 'Orinda', 'Pinole', 'Pittsburg', 'Pleasant Hill', 'Richmond', 'San Pablo', 'San Ramon', 'Walnut Creek', 'Alamo', 'Pacheco', 'Bay Point', 'El Sobrante', 'Oakley', 'Rodeo', 'Discovery Bay'],
    'Del Norte': ['Crescent City'],
    'El Dorado': ['Placerville', 'South Lake Tahoe', 'El Dorado Hills', 'Cool', 'Lotus', 'Cameron Park', 'Kyburz', 'Diamond Springs'],
    'Fresno': ['Biola', 'Clovis', 'Coalinga', 'Firebaugh', 'Fowler', 'Fresno', 'Huron', 'Kerman', 'Kingsburg', 'Mendota', 'Orange Cove', 'Parlier', 'Reedley', 'San Joaquin', 'Sanger', 'Selma', 'Prather', 'Shaver Lake', 'Riverdale', 'Five Points'],
    'Glenn': ['Orland', 'Willows'],
    'Humboldt': ['Arcata', 'Blue Lake', 'Eureka', 'Fortuna', 'Rio Dell', 'Trinidad', 'McKinleyville', 'Ferndale', 'Garberville', 'Loleta', 'Whitethorn', 'Willow Creek'],
    'Imperial': ['Brawley', 'Calexico', 'Calipatria', 'El Centro', 'Holtville', 'Imperial', 'Westmorland'],
    'Inyo': ['Bishop', 'Lone Pine'],
    'Kern': ['Arvin', 'Bakersfield', 'California City', 'Delano', 'Maricopa', 'McFarland', 'Ridgecrest', 'Shafter', 'Taft', 'Tehachapi', 'Wasco', 'Rosamond', 'Edwards AFB', 'Lamont', 'Mojave', 'Lost Hills', 'Kernville', 'Lake Isabella', 'Edwards'],
    'Kings': ['Avenal', 'Corcoran', 'Hanford', 'Lemoore'],
    'Lake': ['Clearlake', 'Lakeport', 'Nice', 'Spring Valley', 'Hidden Valley Lake', 'Kelseyville', 'Lower Lake'],
    'Lassen': ['Susanville', 'Bieber'],
    'Los Angeles': ['Pacific Palisades', 'Valencia', 'Reseda', 'San Pedro', 'City of Industry', 'Northridge', 'North Hollywood', 'Sylmar', 'Sun Valley', 'Artesia', 'Arcadia', 'Venice', 'Sherman Oaks', 'Van Nuys', 'Studio City', 'Granada Hills', 'Rowland Heights', 'Harbor City', 'Tujunga', 'Saugus', 'Highland Park', 'Pacoima', 'Universal City', 'Hollywood', 'East Los Angeles', 'West Hills', 'Cudahy', 'La Crescenta-Montrose', 'Canoga Park','Wilmington', 'Woodland Hills', 'Canyon Country', 'Panorama City', 'Tarzana', 'Winnetka', 'Newhall', 'Castaic', 'Stevenson Ranch', 'Irwindale', 'View Park-Windsor Hills', 'Lomita', 'Marina Del Rey', 'Valley Glen', 'Eagle Rock', 'North Hills', 'Lakewood', 'Arleta', 'Toluca Lake', 'Valley Village', 'Mission Hills', 'Bassett', 'Littlerock', 'Topanga', 'Playa Vista', 'Quartz Hill', 'East Compton', 'Porter Ranch', 'Silver Lake'],
    'Acton': ['Agoura Hills', 'Alhambra', 'Alondra Park', 'Altadena', 'Avalon', 'Azusa', 'Baldwin Park', 'Bell', 'Bell Gardens', 'Bellflower', 'Beverly Hills', 'Burbank', 'Calabasas', 'Carson', 'Cerritos', 'Chatsworth', 'Claremont', 'Commerce', 'Compton', 'Covina', 'Culver City', 'Diamond Bar', 'Downey', 'Duarte', 'El Monte', 'El Segundo', 'Encino', 'Gardena', 'Glendale', 'Glendora', 'Hacienda Heights', 'Hawaiian Gardens', 'Hawthorne', 'Hermosa Beach', 'Huntington Park', 'Industry', 'Inglewood', 'La Canada Flintridge', 'La Mirada', 'La Puente', 'La Verne', 'Lancaster', 'Lawndale', 'Lennox', 'Long Beach', 'Los Angeles', 'Lynwood', 'Malibu', 'Manhattan Beach', 'Maywood', 'Monrovia', 'Montebello', 'Monterey Park', 'Norwalk', 'Palmdale', 'Palos Verdes Estates', 'Paramount', 'Pasadena', 'Pico Rivera', 'Pomona', 'Rancho Palos Verdes', 'Redondo Beach', 'Rolling Hills Estates', 'Rosemead', 'San Dimas', 'San Fernando', 'San Gabriel', 'San Marino', 'Santa Clarita', 'Santa Fe Springs', 'Santa Monica', 'Sierra Madre', 'Signal Hill', 'South El Monte', 'South Gate', 'South Pasadena', 'Temple City', 'Torrance', 'Vernon', 'Walnut', 'West Covina', 'West Hollywood', 'Westlake Village', 'Whittier'],
    'Madera': ['Chowchilla', 'Madera', 'Bass Lake', 'North Fork', 'Coarsegold', 'Oakhurst'],
    'Marin': ['Belvedere', 'Corte Madera', 'Fairfax', 'Larkspur', 'Mill Valley', 'Novato', 'Ross', 'San Anselmo', 'San Rafael', 'Sausalito', 'Tiburon', 'Olema', 'Point Reyes Station', 'Greenbrae', 'Stinson Beach', 'Tomales'],
    'Mariposa': ['Mariposa'],
    'Mendocino': ['Fort Bragg', 'Point Arena', 'Ukiah', 'Willits', 'Mendocino', 'Little River', 'Laytonville', 'Philo', 'Gualala', 'Redwood Valley', 'Elk', 'Boonville'],
    'Merced': ['Atwater', 'Dos Palos', 'Gustine', 'Livingston', 'Los Banos', 'Merced', 'Delhi', 'Santa Nella'],
    'Modoc': ['Alturas'],
    'Mono': ['Mammoth Lakes', 'June Lake'],
    'Monterey': ['Carmel-by-the-Sea', 'Del Rey Oaks', 'Gonzales', 'Greenfield', 'King City', 'Marina', 'Monterey', 'Pacific Grove', 'Salinas', 'Sand City', 'Seaside', 'Soledad', 'Carmel Valley', 'Pebble Beach', 'Castroville', 'Pajaro', 'Royal Oaks', 'Prunedale', 'Aromas','Carmel-By-The-Sea'],
    'Napa': ['American Canyon', 'Calistoga', 'Napa', 'St. Helena', 'Yountville', 'St Helena', 'Rutherford', 'Santa Elena'],
    'Nevada': ['Grass Valley', 'Nevada City', 'Truckee', 'Cisco Grove', 'North San Juan', 'Penn Valley'],
    'Orange': ['Aliso Viejo', 'Anaheim', 'Brea', 'Buena Park', 'Costa Mesa', 'Cypress', 'Dana Point', 'Fountain Valley', 'Fullerton', 'Garden Grove', 'Huntington Beach', 'Irvine', 'La Habra', 'La Palma', 'Laguna Beach', 'Laguna Hills', 'Laguna Niguel', 'Laguna Woods', 'Lake Forest', 'Los Alamitos', 'Mission Viejo', 'Newport Beach', 'Orange', 'Placentia', 'Rancho Santa Margarita', 'San Clemente', 'San Juan Capistrano', 'Santa Ana', 'Seal Beach', 'Stanton', 'Tustin', 'Villa Park', 'Westminster', 'Yorba Linda', 'Foothill Ranch', 'Ladera Ranch', 'Silverado', 'Trabuco Canyon', 'Newport Coast'],
    'Placer': ['Auburn', 'Colfax', 'Lincoln', 'Loomis', 'Rocklin', 'Roseville', 'Kings Beach', 'Tahoe City', 'Granite Bay', 'Olympic Valley', 'Newcastle', 'Homewood'],
    'Plumas': ['Portola', 'Quincy', 'Chester', 'Lake Almanor', 'Blairsden-Graeagle'],
    'Riverside': ['Banning', 'Beaumont', 'Blythe', 'Calimesa', 'Canyon Lake', 'Cathedral City', 'Coachella', 'Corona', 'Desert Hot Springs', 'Eastvale', 'Hemet', 'Indian Wells', 'Indio', 'Jurupa Valley', 'La Quinta', 'Lake Elsinore', 'Menifee', 'Moreno Valley', 'Murrieta', 'Norco', 'Palm Desert', 'Palm Springs', 'Perris', 'Rancho Mirage', 'Riverside', 'San Jacinto', 'Temecula', 'Wildomar', 'Thousand Palms', 'Cabazon', 'March Air Reserve Base', 'Idyllwild-Pine Cove', 'Thermal', 'Bermuda Dunes', 'Mira Loma', 'Winchester', 'Anza', 'Mecca', 'Romoland', 'Sun City'],
    'Sacramento': ['Citrus Heights', 'Elk Grove', 'Folsom', 'Galt', 'Isleton', 'Rancho Cordova', 'Sacramento', 'Antelope', 'Arden-Arcade', 'Carmichael', 'Clay', 'Courtland', 'Elverta', 'Fair Oaks', 'Florin', 'Foothill Farms', 'Franklin', 'Fruitridge Pocket', 'Gold River', 'La Riviera', 'Lemon Hill', 'Mather', 'North Highlands', 'Orangevale', 'Parkway', 'Rancho Murieta', 'Rio Linda', 'Rosemont', 'Vineyard', 'Walnut Grove', 'Wilton', 'Hood', 'Rio Linda'],
    'San Benito': ['Hollister', 'San Juan Bautista', 'Tres Pinos'],
    'San Bernardino': ['Adelanto', 'Apple Valley', 'Barstow', 'Big Bear Lake', 'Chino', 'Chino Hills', 'Colton', 'Fontana', 'Grand Terrace', 'Hesperia', 'Highland', 'Loma Linda', 'Montclair', 'Needles', 'Ontario', 'Rancho Cucamonga', 'Redlands', 'Rialto', 'San Bernardino', 'Twentynine Palms', 'Upland', 'Victorville', 'Yucaipa', 'Yucca Valley', 'Joshua Tree', 'Crestline', 'Lake Arrowhead', 'Alta Loma', 'Joshua Tree', 'Oro Grande', 'Yermo', 'Bloomington','Phelan','Helendale','Fort Irwin','Running Springs'],
    'San Diego': ['Carlsbad', 'Chula Vista', 'Coronado', 'Del Mar', 'El Cajon', 'Encinitas', 'Escondido', 'Imperial Beach', 'La Mesa', 'Lemon Grove', 'National City', 'Oceanside', 'Poway', 'San Diego', 'San Marcos', 'Santee', 'Solana Beach', 'Vista', 'Alpine', 'Bonita', 'Borrego Springs', 'Fallbrook', 'Jamul', 'Julian', 'Lakeside', 'Pine Valley', 'Ramona', 'Ranchita', 'Rancho Santa Fe', 'Spring Valley', 'Camp Pendleton North', 'Bonsall', 'Pala', 'Carmel Mountain Ranch', 'Pauma Valley', 'Julian','La Jolla','Camp Pendleton'],
    'San Francisco': ['San Francisco'],
    'San Joaquin': ['Escalon', 'Lathrop', 'Lodi', 'Manteca', 'Ripon', 'Stockton', 'Tracy', 'Acampo', 'French Camp', 'Lockeford', 'Thornton', 'Lockeford', 'Acampo'],
    'San Luis Obispo': ['Arroyo Grande', 'Atascadero', 'Grover Beach', 'Morro Bay', 'Paso Robles', 'Pismo Beach', 'San Luis Obispo', 'Baywood-Los Osos', 'Santa Margarita', 'Cayucos', 'Oceano', 'Templeton', 'Nipomo', 'Cambria', 'San Simeon', 'Los Osos'],
    'San Mateo': ['Atherton', 'Belmont', 'Brisbane', 'Burlingame', 'Colma', 'Daly City', 'East Palo Alto', 'Foster City', 'Half Moon Bay', 'Hillsborough', 'Menlo Park', 'Millbrae', 'Pacifica', 'Portola Valley', 'Redwood City', 'San Bruno', 'San Carlos', 'San Mateo', 'South San Francisco', 'Woodside'],
    'Santa Barbara': ['Buellton', 'Carpinteria', 'Goleta', 'Guadalupe', 'Lompoc', 'Santa Barbara', 'Santa Maria', 'Solvang', 'Orcutt', 'Los Alamos','Los Olivos','Montecito','Isla Vista','Vandenberg AFB'],
    'Santa Clara': ['Campbell', 'Cupertino', 'Gilroy', 'Los Altos', 'Los Altos Hills', 'Los Gatos', 'Milpitas', 'Monte Sereno', 'Morgan Hill', 'Mountain View', 'Palo Alto', 'San Jose', 'Santa Clara', 'Saratoga', 'Sunnyvale','Stanford'],
    'Santa Cruz': ['Capitola', 'Santa Cruz', 'Scotts Valley', 'Watsonville', 'Boulder Creek', 'Freedom','Aptos','Soquel','Felton'],
    'Shasta': ['Anderson', 'Redding', 'Shasta Lake', 'Burney', 'McArthur', 'Platina', 'Lakehead', 'Fall River Mills', 'Cottonwood'],
    'Sierra': ['Loyalton', 'Sierra City'],
    'Siskiyou': ['Dorris', 'Dunsmuir', 'Etna', 'Fort Jones', 'Montague', 'Mount Shasta', 'Tulelake', 'Weed', 'Yreka', 'Mt Shasta', 'Mount Shasta'],
    'Solano': ['Benicia', 'Dixon', 'Fairfield', 'Rio Vista', 'Suisun City', 'Vacaville', 'Vallejo'],
    'Sonoma': ['Cloverdale', 'Cotati', 'Healdsburg', 'Petaluma', 'Rohnert Park', 'Santa Rosa', 'Sebastopol', 'Sonoma', 'Windsor', 'Bodega Bay', 'Guerneville', 'Geyserville', 'Forestville', 'Monte Rio'],
    'Stanislaus': ['Ceres', 'Hughson', 'Modesto', 'Newman', 'Oakdale', 'Patterson', 'Riverbank', 'Turlock', 'Waterford', 'Salida', 'Keyes', 'Westley'],
    'Sutter': ['Live Oak', 'Yuba City', 'Sutter'],
    'Tehama': ['Corning', 'Red Bluff', 'Tehama'],
    'Trinity': ['Weaverville', 'Wildwood', 'Lewiston'],
    'Tulare': ['Dinuba', 'Exeter', 'Farmersville', 'Lindsay', 'Porterville', 'Tulare', 'Visalia', 'Woodlake', 'Alpaugh', 'Orosi', 'Springville','Earlimart','Pixley','Terra Bella','Ivanhoe','Strathmore','Richgrove'],
    'Tuolumne': ['Sonora', 'Jamestown', 'Columbia', 'Pinecrest', 'Groveland'],
    'Ventura': ['Camarillo', 'Fillmore', 'Moorpark', 'Ojai', 'Oxnard', 'Port Hueneme', 'Santa Paula', 'Simi Valley', 'Thousand Oaks', 'Ventura', 'Oak Park','Newbury Park','Somis'],
    'Yolo': ['Davis', 'West Sacramento', 'Winters', 'Woodland', 'Zamora'],
    'Yuba': ['Marysville', 'Wheatland','Linda']
}

In [227]:
# Obtener solo las claves del dic
lista_condados = list(condados_a_ciudades.keys())
lista_condados_lower = [condado.lower() for condado in lista_condados]  # Normalizar la lista de condados a min√∫sculas

In [228]:
len(lista_condados)

59

In [229]:
# Modificar la columna RegionName y filtrar
df_alquilerCONDADO['RegionName'] = df_alquilerCONDADO['RegionName'].str.replace(' County', '').str.strip()

In [230]:
# Filtrar el DataFrame
df_alquilerCONDADO = df_alquilerCONDADO[df_alquilerCONDADO['RegionName'].str.lower().isin(lista_condados_lower)]
df_alquilerCONDADO = df_alquilerCONDADO.drop_duplicates(subset='RegionName')

In [231]:
df_alquilerCONDADO['County'] = df_alquilerCONDADO['RegionName']
df_alquilerCONDADO['Rent'] = df_alquilerCONDADO['renta'].astype(float).round(2)

df_alquilerCONDADO = df_alquilerCONDADO.drop(columns=['renta'])
df_alquilerCONDADO = df_alquilerCONDADO.drop(columns=['RegionName'])

In [232]:
df_alquilerCONDADO

               County     Rent
0         Los Angeles  2769.27
4           San Diego  2932.61
5              Orange  3060.83
6               Kings  3296.49
9           Riverside  2511.54
13     San Bernardino  2370.01
16        Santa Clara  3342.43
19            Alameda  2837.29
23         Sacramento  2134.27
37       Contra Costa  2793.72
46             Fresno  1827.36
61               Kern  1686.09
65      San Francisco  3393.74
74            Ventura  2894.47
83        San Joaquin  2332.23
85          San Mateo  3314.22
91               Lake  1916.05
124        Stanislaus  1867.47
144            Sonoma  2541.35
151            Tulare  1633.63
158            Solano  2387.06
159     Santa Barbara  3123.27
161          Monterey  2494.66
177            Placer  2474.96
246   San Luis Obispo  2551.74
248            Merced  1848.91
253        Santa Cruz  3309.87
265             Marin  3556.81
313             Butte  1543.44
314              Yolo  2278.48
349         El Dorado  2388.31
366            Shasta  1454.96
371          Imperial      NaN
428            Madera  1920.64
468              Napa  3023.77
472          Humboldt  1398.54
593            Nevada  2593.04
602            Sutter  1889.51
645         Mendocino      NaN
699              Yuba      NaN
795            Tehama      NaN
815        San Benito      NaN
965         Calaveras      NaN
978          Siskiyou      NaN
1193             Mono      NaN

# ------------------------------------------------------------------------------

In [233]:
# Ruta del archivo .xlsx
file_path = r'C:\Users\Usuario\Desktop\HENRY\PROYECTO FINAL\CENSO\percapitaingresoCONDADO.xlsx'

# Cargar el archivo .xlsx y seleccionar columnas espec√≠ficas
columnas_necesarias = ['County', 'ingreso']
df_percapitaingresoCONDAD = pd.read_excel(file_path, usecols=columnas_necesarias)

In [234]:
df_percapitaingresoCONDAD = df_percapitaingresoCONDAD[df_percapitaingresoCONDAD['County'].str.lower().isin(lista_condados_lower)]
df_percapitaingresoCONDAD = df_percapitaingresoCONDAD.drop_duplicates(subset='County')

df_percapitaingresoCONDAD['Per capita income'] = df_percapitaingresoCONDAD['ingreso']
df_percapitaingresoCONDAD = df_percapitaingresoCONDAD.drop(columns=['ingreso'])

In [235]:
df_percapitaingresoCONDAD

              County  Per capita income
114       Santa Cruz            47898.0
168           Nevada            40501.0
196          Alameda            97754.0
197           Alpine            67551.0
198           Amador            48463.0
199            Butte            54974.0
200        Calaveras            56001.0
201           Colusa            55502.0
202     Contra Costa            95047.0
203        Del Norte            43677.0
204        El Dorado            82062.0
205           Fresno            50549.0
206            Glenn            51055.0
207         Humboldt            54043.0
208         Imperial            45188.0
209             Inyo            61501.0
210             Kern            44862.0
211            Kings            42525.0
212             Lake            45623.0
213           Lassen            40700.0
214      Los Angeles            74142.0
215           Madera            46406.0
216            Marin           171177.0
217         Mariposa            61230.0
218        Mendocino            57310.0
219           Merced            46188.0
220            Modoc            56559.0
221             Mono            65296.0
222         Monterey            65123.0
223             Napa            86863.0
225           Orange            83553.0
226           Placer            81791.0
227           Plumas            59387.0
228        Riverside            51415.0
229       Sacramento            61558.0
230       San Benito            61693.0
231   San Bernardino            49270.0
232        San Diego            74326.0
233    San Francisco           155819.0
234      San Joaquin            54183.0
235  San Luis Obispo            67951.0
236        San Mateo           175070.0
237    Santa Barbara            75720.0
238      Santa Clara           144399.0
240           Shasta            54120.0
241           Sierra            47877.0
242         Siskiyou            51788.0
243           Solano            58273.0
244           Sonoma            77900.0
245       Stanislaus            51015.0
246           Sutter            52005.0
247           Tehama            47315.0
248          Trinity            36314.0
249           Tulare            47295.0
250         Tuolumne            52806.0
251          Ventura            76375.0
252             Yolo            64279.0
253             Yuba            48204.0

# ------------------------------------------------------------------------------

In [236]:
# Ruta del archivo .xlsx
file_path = r'C:\Users\Usuario\Desktop\HENRY\PROYECTO FINAL\CENSO\precioviviendaCONDADO.xlsx'

# Cargar el archivo .xlsx y seleccionar columnas espec√≠ficas
columnas_necesarias = ['State.county', 'Costo Vivienda']
df_precioviviendaCONDADO = pd.read_excel(file_path, usecols=columnas_necesarias)

In [237]:
# Filtrar el DataFrame seg√∫n 'State.county' y conservar solo los condados de la lista
df_precioviviendaCONDADO = df_precioviviendaCONDADO[df_precioviviendaCONDADO['State.county'].str.lower().isin(lista_condados_lower)]

# Asignar la columna 'County' sin cambiar a min√∫sculas
df_precioviviendaCONDADO['County'] = df_precioviviendaCONDADO['State.county']


# Eliminar la columna original 'State.county'
df_precioviviendaCONDADO = df_precioviviendaCONDADO.drop(columns=['State.county'])

In [238]:
# Crear la nueva columna 'Property Cost' a partir de 'Costo Vivienda'
df_precioviviendaCONDADO['Property Cost'] = df_precioviviendaCONDADO['Costo Vivienda']

# Eliminar la columna original 'Costo Vivienda'
df_precioviviendaCONDADO = df_precioviviendaCONDADO.drop(columns=['Costo Vivienda'])

In [239]:
df_precioviviendaCONDADO

             County  Property Cost
0       Los Angeles         792500
7           Alameda        1250000
8      Contra Costa         844440
9             Marin        1475000
10             Napa        1055000
11    San Francisco        1576000
12        San Mateo        1950000
13      Santa Clara        1852500
14           Solano         599000
15           Sonoma         850000
16         Imperial         336500
17      Los Angeles         882010
20   San Bernardino         495000
21        San Diego        1000000
22          Ventura         915000
23         Monterey         897000
24  San Luis Obispo         868810
25    Santa Barbara        1295000
26       Santa Cruz        1200000
27           Fresno         425000
28            Glenn         321000
29             Kern         394500
30            Kings         382500
31           Madera         453000
32           Merced         385000
33           Placer         669000
34       Sacramento         535000
35       San Benito         777550
36      San Joaquin         535000
37       Stanislaus         465000
38           Tulare         372000
39            Butte         436250
40           Lassen         225000
41           Plumas         412000
42           Shasta         365000
44           Tehama         312050
45          Trinity         205000
46           Amador         490000
47        Calaveras         475000
48        Del Norte         382500
49        El Dorado         657000
50         Humboldt         421920
51             Lake         325000
52         Mariposa         480000
53        Mendocino         560000
54             Mono         970000
55           Nevada         555000
56           Sutter         425000
57         Tuolumne         389500
58             Yolo         622500
59             Yuba         449500

# ------------------------------------------------------------------------------

In [240]:
print(df_percapitaingresoCONDAD.columns)
print(df_alquilerCONDADO.columns)
print(df_precioviviendaCONDADO.columns)

Index(['County', 'Per capita income'], dtype='object')
Index(['County', 'Rent'], dtype='object')
Index(['County', 'Property Cost'], dtype='object')

In [241]:
# Mergear df1 y df2 con outer join
df_merged = pd.merge(df_percapitaingresoCONDAD, df_alquilerCONDADO, on='County', how='outer')

# Mergear el resultado con df3 tambi√©n con outer join
df_datosEconomicos = pd.merge(df_merged, df_precioviviendaCONDADO, on='County', how='outer')

In [242]:
df_datosEconomicos.columns

Index(['County', 'Per capita income', 'Rent', 'Property Cost'], dtype='object')

In [243]:
# Eliminar filas duplicadas basadas en la columna 'county'
df_datosEconomicos = df_datosEconomicos.drop_duplicates(subset='County')

In [250]:
nuevo_condado = pd.DataFrame({
    'County': ['Acton'],  # Reemplaza 'nuevo_condado' por el nombre real
    'Per capita income': [None],  # Puedes usar un valor realista o None
    'Rent': [None],  # Puedes usar un valor realista o None
    'Property Cost': [None]  # Puedes usar un valor realista o None
})

# Concatenar el DataFrame con el existente
df_datosEconomicos = pd.concat([df_datosEconomicos, nuevo_condado], ignore_index=True)

In [251]:
# Funci√≥n para generar un valor aleatorio cerca de la mediana
def valor_aleatorio_cercano(mediana):
    rango = 0.1 * mediana  # Ajusta el rango seg√∫n sea necesario (10% de la mediana)
    return np.random.uniform(mediana - rango, mediana + rango)

# Rellenar los valores vac√≠os con valores aleatorios cercanos a la mediana
for columna in ['Per capita income', 'Rent', 'Property Cost']:
    mediana = df_datosEconomicos[columna].median()  # Calcular la mediana una vez por columna
    for index, row in df_datosEconomicos.iterrows():
        if pd.isna(row[columna]):
            df_datosEconomicos.at[index, columna] = round(valor_aleatorio_cercano(mediana), 2)

In [253]:
for columna in ['Per capita income', 'Rent', 'Property Cost']:
    df_datosEconomicos[columna] = df_datosEconomicos[columna].astype(int)

In [254]:
df_datosEconomicos

             County  Per capita income  Rent  Property Cost
0           Alameda              97754  2837        1250000
1            Alpine              67551  2398         508142
2            Amador              48463  2742         490000
3             Butte              54974  1543         436250
4         Calaveras              56001  2684         475000
5            Colusa              55502  2677         491927
6      Contra Costa              95047  2793         844440
7         Del Norte              43677  2273         382500
8         El Dorado              82062  2388         657000
9            Fresno              50549  1827         425000
10            Glenn              51055  2510         321000
11         Humboldt              54043  1398         421920
12         Imperial              45188  2341         336500
13             Inyo              61501  2628         493938
14             Kern              44862  1686         394500
15            Kings              42525  3296         382500
16             Lake              45623  1916         325000
17           Lassen              40700  2253         225000
18      Los Angeles              74142  2769         792500
19           Madera              46406  1920         453000
20            Marin             171177  3556        1475000
21         Mariposa              61230  2385         480000
22        Mendocino              57310  2540         560000
23           Merced              46188  1848         385000
24            Modoc              56559  2372         547547
25             Mono              65296  2338         970000
26         Monterey              65123  2494         897000
27             Napa              86863  3023        1055000
28           Nevada              40501  2593         555000
29           Orange              83553  3060         514461
30           Placer              81791  2474         669000
31           Plumas              59387  2439         412000
32        Riverside              51415  2511         492009
33       Sacramento              61558  2134         535000
34       San Benito              61693  2643         777550
35   San Bernardino              49270  2370         495000
36        San Diego              74326  2932        1000000
37    San Francisco             155819  3393        1576000
38      San Joaquin              54183  2332         535000
39  San Luis Obispo              67951  2551         868810
40        San Mateo             175070  3314        1950000
41    Santa Barbara              75720  3123        1295000
42      Santa Clara             144399  3342        1852500
43       Santa Cruz              47898  3309        1200000
44           Shasta              54120  1454         365000
45           Sierra              47877  2385         555041
46         Siskiyou              51788  2584         479270
47           Solano              58273  2387         599000
48           Sonoma              77900  2541         850000
49       Stanislaus              51015  1867         465000
50           Sutter              52005  1889         425000
51           Tehama              47315  2387         312050
52          Trinity              36314  2440         205000
53           Tulare              47295  1633         372000
54         Tuolumne              52806  2713         389500
55          Ventura              76375  2894         915000
56             Yolo              64279  2278         622500
57             Yuba              48204  2291         449500
58            Acton              51975  2275         500227

In [256]:
# Guardar el DataFrame en un archivo Parquet en una ruta espec√≠fica
ruta = r'C:\Users\Usuario\Desktop\HENRY\PROYECTO FINAL\datosEconomicos.parquet'
df_datosEconomicos.to_parquet(ruta, index=False)